name: Add Snap Request
description: Request to add a new Snap to the registry.
labels:
  - add request
body:
  - type: input
    id: snap-id
    attributes:
      label: Snap ID
      description: What is the ID of the Snap you want to add? This should be the name of the package on npm, starting with the `npm:` prefix.
      placeholder: "npm:package-name"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What does this Snap do? This should be a brief description of the Snap's functionality and purpose, and is shown on the Snaps Directory.
      placeholder: This Snap does X, Y, and Z. It is useful for A, B, and C.
    validations:
      required: true
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Provide a brief summary of the Snap. This is shown on the Snaps Directory.
      placeholder: This Snap does X, Y, and Z.
    validations:
      required: true
  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What category does this Snap belong to? This is used to help users find Snaps in the Snaps Directory.
      options:
        - account management
        - interoperability
        - notifications
        - transaction insights
    validations:
      required: true
  - type: input
    id: website
    attributes:
      label: Website
      description: Where can users find more information about this Snap? This should be a link to the Snap's website or dapp.
      placeholder: "https://example.com"
    validations:
      required: true
  - type: input
    id: repository
    attributes:
      label: Repository
      description: Where is the source code for this Snap? This should be a link to the Snap's GitHub repository.
      placeholder: "https://github.com/..."
    validations:
      required: true
  - type: checkboxes
    id: open-source
    attributes:
      label: Open Source
      description: Is the source code for this Snap open source, including any front-end and back-end code, smart contracts, and other components?
      options:
        - label: The Snap is fully open source.
  - type: input
    id: author
    attributes:
      label: Author
      description: Who is the author of this Snap?
      placeholder: John Doe
    validations:
      required: true
  - type: input
    id: author-website
    attributes:
      label: Author Website
      description: Where can we find more information about the author?
      placeholder: "https://johndoe.com"
    validations:
      required: true
  - type: input
    id: support-page
    attributes:
      label: Support Page
      description: Where can users get support for this Snap? This can be an email address or a link to a support page.
      placeholder: mailto:support@example.com
  - type: input
    id: faq
    attributes:
      label: FAQ
      description: Where can users find frequently asked questions about this Snap?
      placeholder: "https://example.com/faq"
  - type: input
    id: knowledge-base
    attributes:
      label: Knowledge Base
      description: Where can users find documentation and tutorials for this Snap?
      placeholder: "https://example.com/docs"
