name: Process Snap request
concurrency: issue-${{ github.event.number }}

on:
  issues:
    types:
      - opened
      - edited
      - reopened

jobs:
  process-add-request:
    name: Add Snap request
    if: contains(github.event.issue.labels.*.name, 'add request')
    runs-on: ubuntu-latest
    steps:
      - name: Dump context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Install Yarn dependencies
        run: yarn --immutable

      - name: Build
        run: yarn build

      - name: Get issue data
        id: issue-parser
        uses: stefanbuck/github-issue-parser@v3
        with:
          template-path: .github/ISSUE_TEMPLATE/add-snap-request.yml

      - name: Update registry
        run: yarn add-snap --snap-id ${{ steps.issue-parser.outputs.issueparser_snap-id }}

      - name: Configure Git
        run: |
          git config --global user.name 'MetaMask Bot'
          git config --global user.email 'metamaskbot@users.noreply.github.com'
          git checkout -b "request/add/${{ github.event.number }}"

      - name: Commit registry
        run: |
          git add src/registry.json
          git commit -m "Add ${{ steps.issue-parser.outputs.issueparser_snap-id }} to registry"
          git push --set-upstream origin "request/add/${{ github.event.number }}"

      - name: Create pull request
        run: gh pr create --title "Add ${{ steps.issue-parser.outputs.issueparser_snap-id }} to registry" --body "This pull request adds ${{ steps.issue-parser.outputs.issueparser_snap-id }} to the registry." --base main --head "request/add/${{ github.event.number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
